{
    'name': 'MoMo Payment',
    'version': '1.0',
    'category': 'Payment',
    'sequence': 1,
    'summary': 'Integration with MoMo payment gateway',
    'description': 'Module to integrate MoMo payment gateway with Odoo',
    'author': 'Hai Nhat',
    'depends': ['base', 'payment', 'website_sale'],
    'data': [
        'security/ir.model.access.csv',
        'security/momo_transaction_security.xml',
        'views/payment_momo_view.xml',
        'views/payment_momo_template.xml',
        'views/momo_transaction_pending_views.xml',
        'views/momo_transaction_retry_views.xml',
        'data/cron_data.xml',
        'data/payment_provider_data.xml',
        'data/payment_method_data.xml',
    ],
    "post_init_hook": "post_init_hook",
    "uninstall_hook": "uninstall_hook",
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
